name: Export PowerXForm from Dev and Push to Main

on:
  push:
    branches:
      - 'dev/*'
  workflow_dispatch:

jobs:
  export-solution:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-cli@v1

    - name: Authenticate with Power Platform (SPN)
      run: |
        pac auth clear
        pac auth create --name DevEnv `
          --clientId "${{ secrets.CLIENT_ID }}" `
          --clientSecret "${{ secrets.CLIENT_SECRET }}" `
          --tenant "${{ secrets.TENANT_ID }}" `
          --url "https://tdlproduct.crm.dynamics.com"

    - name: Export PowerXForm Solution
      run: |
        mkdir -p ./solutions
        pac solution export `
          --name PowerXForm `
          --path ./solutions/PowerXForm.zip `
          --type Unmanaged `
          --overwrite

    - name: Commit and push exported solution to main
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        git add ./solutions/PowerXForm.zip
        git commit -m "Exported PowerXForm solution from ${{ github.ref_name }} on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

        git fetch origin main
        git checkout main
        git checkout ${{ github.ref_name }} -- ./solutions/PowerXForm.zip

        git add ./solutions/PowerXForm.zip
        git commit -m "Promoted PowerXForm solution from ${{ github.ref_name }}" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger import workflow on main
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: solution-exported
        client-payload: |
          {
            "run_number": "${{ github.run_number }}",
            "solution_name": "PowerXForm",
            "export_branch": "${{ github.ref_name }}"
          }
