name: Export and Unpack PowerXForm from Dev

on:
  push:
    branches: [ 'dev/*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Who Am I (SPN Auth)
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          authentication-type: 'SPN'
          environment-url: 'https://tdlproduct.crm.dynamics.com/'
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}

      - name: Export PowerXForm
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          authentication-type: 'SPN'
          environment-url: 'https://tdlproduct.crm.dynamics.com/'
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-name: PowerXForm
          solution-output-file: out/exported/PowerXForm.zip

      - name: Unpack solution
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: out/exported/PowerXForm.zip
          solution-folder: out/solutions/PowerXForm
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Commit unpacked solution
        uses: microsoft/powerplatform-actions/branch-solution@v0
        with:
          solution-folder: out/solutions/PowerXForm
          solution-target-folder: solutions/PowerXForm
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
