name: Export and Unpack Power Platform Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: 'https://mayank1.crm.dynamics.com'
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-name: 'My App'
        solution-output-file: 'MyApp.zip'
        working-directory: 'out'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/MyApp.zip'
        solution-folder: 'out/solutions/My App'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: 'https://mayank1.crm.dynamics.com'
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'out/solutions/My App'
        solution-target-folder: 'src/solutions/My App'
        token: ${{ secrets.GITHUB_TOKEN }}
