name: Export Only Changed Solutions

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  export:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Detect Changed Solutions
      id: detect_changes
      shell: bash
      run: |
        git fetch origin main --depth=1
        git diff --name-only origin/main...HEAD |
          grep '^src/solutions/' |
          awk -F/ '{ print $3 }' |
          sort -u > changed_solutions.txt

        if [[ -s changed_solutions.txt ]]; then
          echo "Detected changes:"
          cat changed_solutions.txt
          echo "changed_solutions=$(cat changed_solutions.txt | paste -sd ',' -)" >> $GITHUB_OUTPUT
        else
          echo "No changes detected."
          echo "changed_solutions=" >> $GITHUB_OUTPUT

    - name: Set Changed List
      run: echo "Changed solutions: ${{ steps.detect_changes.outputs.changed_solutions }}"

    - name: Export Solution: MyApp
      if: contains(steps.detect_changes.outputs.changed_solutions, 'MyApp')
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: 'https://mayank1.crm.dynamics.com'
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-name: 'MyApp'
        solution-output-file: 'out/MyApp.zip'

    - name: Unpack Solution: MyApp
      if: contains(steps.detect_changes.outputs.changed_solutions, 'MyApp')
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/MyApp.zip'
        solution-folder: 'src/solutions/MyApp'
        solution-type: 'Unmanaged'
        overwrite-files: true
