name: Export and Unpack Only Changed Power Platform Solutions

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  export:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Detect Changed Solutions
      id: detect_changes
      shell: bash
      run: |
        git fetch origin main --depth=1
        git diff --name-only origin/main...HEAD |
        grep '^src/solutions/' |
        awk -F/ '{ print $3 }' |
        sort -u > changed_solutions.txt

        if [[ -s changed_solutions.txt ]]; then
          echo "Changed solutions:"
          cat changed_solutions.txt
          echo "changed=$(cat changed_solutions.txt | tr '\n' ' ')" >> $GITHUB_OUTPUT
        else
          echo "No changes detected in solutions."
          echo "changed=" >> $GITHUB_OUTPUT
        fi

    - name: Export and Unpack Solutions
      if: steps.detect_changes.outputs.changed != ''
      shell: bash
      env:
        ENV_URL: 'https://mayank1.crm.dynamics.com'
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for solution in ${{ steps.detect_changes.outputs.changed }}; do
          echo "=== Exporting $solution ==="

          echo "::group::Export $solution"
          gh workflow run microsoft/powerplatform-actions/export-solution@v1 \
            --field environment-url=$ENV_URL \
            --field tenant-id=$TENANT_ID \
            --field app-id=$CLIENT_ID \
            --field client-secret=$CLIENT_SECRET \
            --field solution-name=$solution \
            --field solution-output-file=out/$solution.zip
          echo "::endgroup::"

          echo "::group::Unpack $solution"
          gh workflow run microsoft/powerplatform-actions/unpack-solution@v1 \
            --field solution-file=out/$solution.zip \
            --field solution-folder=out/solutions/$solution \
            --field solution-type=Unmanaged \
            --field overwrite-files=true
          echo "::endgroup::"

          echo "::group::Publish $solution"
          gh workflow run microsoft/powerplatform-actions/publish-solution@v1 \
            --field environment-url=$ENV_URL \
            --field tenant-id=$TENANT_ID \
            --field app-id=$CLIENT_ID \
            --field client-secret=$CLIENT_SECRET
          echo "::endgroup::"

          echo "::group::Stage $solution"
          gh workflow run microsoft/powerplatform-actions/branch-solution@v1 \
            --field solution-folder=out/solutions/$solution \
            --field solution-target-folder=src/solutions/$solution \
            --field repo-token=$GITHUB_TOKEN
          echo "::endgroup::"
        done
