jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clean temp folder (ignore errors)
      run: |
        Get-ChildItem -Path $env:TEMP -Recurse -Force -ErrorAction SilentlyContinue | 
        Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
      shell: powershell

    - name: Install Power Platform CLI globally
      run: |
        dotnet tool uninstall -g Microsoft.PowerApps.CLI || echo "Not installed"
        dotnet tool install -g Microsoft.PowerApps.CLI --version 1.43.6
      shell: powershell

    - name: Check pac CLI version and path
      run: |
        pac --version
        Get-Command pac
      shell: powershell

    - name: Create output directory
      run: mkdir out
      shell: powershell

    - name: Export Solution CLI (manual)
      run: |
        pac auth create --url https://mayank1.crm.dynamics.com --name default --tenant ${{ secrets.TENANT_ID }} --applicationId ${{ secrets.CLIENT_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }}
        pac solution export --name "My App" --path "out/MyApp.zip" --publisherPrefix "yourPublisherPrefix"
      shell: powershell

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/MyApp.zip'
        solution-folder: 'out/solutions/My App'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: 'https://mayank1.crm.dynamics.com'
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'out/solutions/My App'
        solution-target-folder: 'src/solutions/My App'
        token: ${{ secrets.GITHUB_TOKEN }}
