# .github/workflows/import-solution.yml  
# This file should be on the main branch
name: Import to Main Environment

on:
  repository_dispatch:
    types: [solution-exported]
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'solutions/*.zip'

jobs:
  import:
    runs-on: ubuntu-latest
    environment: production  # Use if you have environment protection rules
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install Power Platform CLI
      run: |
        dotnet tool install --global Microsoft.PowerApps.CLI.Tool
    
    - name: Validate solution file
      run: |
        ZIP_PATH=$(find solutions -name "*.zip" | head -n 1)
        if [ -n "$ZIP_PATH" ] && [ -f "$ZIP_PATH" ]; then
          echo "✓ Solution file found: $ZIP_PATH"
          ls -la "$ZIP_PATH"
        else
          echo "✗ No solution file found in solutions directory"
          ls -la solutions/ || echo "Solutions directory not found"
          exit 1
        fi
    
    - name: Authenticate to Main Environment
      run: |
        pac auth clear
        pac auth create --url https://org10300a3d.crm.dynamics.com \
          --clientId ${{ secrets.CLIENT_ID }} \
          --clientSecret ${{ secrets.CLIENT_SECRET }} \
          --tenant ${{ secrets.TENANT_ID }}
    
    - name: Import solution to Main Environment
      run: |
        ZIP_PATH=$(find solutions -name "*.zip" | head -n 1)
        echo "Importing solution: $ZIP_PATH"
        pac solution import --path "$ZIP_PATH" --force-overwrite
        echo "✓ Solution imported successfully"
    
    - name: Run post-import validation
      run: |
        echo "Running post-import validation..."
        
        # List solutions to verify import
        pac solution list
        
        echo "✓ Post-import validation completed"
    
    - name: Notify import status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "🎉 Solution successfully imported to main environment"
          echo "Environment: https://org10300a3d.crm.dynamics.com"
          echo "Branch: ${{ github.event.client_payload.export_branch || github.ref_name }}"
          echo "Run number: ${{ github.event.client_payload.run_number || github.run_number }}"
        else
          echo "❌ Solution import failed"
          echo "Check the logs for details"
        fi