name: Pack and Import Power Platform Solution

on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'Name of the solution to import'
        required: true
        default: 'MyApp'

jobs:
  pack-import:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Pack solution folder into zip
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: 'src/solutions/${{ github.event.inputs.solution-name }}'
        solution-file: 'out/${{ github.event.inputs.solution-name }}.zip'
        solution-type: 'Unmanaged'

    - name: Import solution into target environment
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: 'https://org54c415c4.crm.dynamics.com'
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-file: 'out/${{ github.event.inputs.solution-name }}.zip'
        publish-changes: true
        force-overwrite: true

    - name: Publish All Customizations
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: 'https://org54c415c4.crm.dynamics.com'
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
