name: Export from Dev Environment

on:
  push:
    branches:
      - 'dev/*'

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool

      - name: Authenticate
        run: |
          pac auth clear
          pac auth create --url https://mayank1.crm.dynamics.com \
            --clientId ${{ secrets.CLIENT_ID }} \
            --clientSecret ${{ secrets.CLIENT_SECRET }} \
            --tenant ${{ secrets.TENANT_ID }}

      - name: Export unmanaged solution
        run: |
          mkdir -p solutions
          pac solution export \
            --name PowerXform \
            --outputDirectory solutions \
            --type Unmanaged \
            --overwrite

      - name: Commit and push solution
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add solutions/
          git commit -m "Exported PowerXform from dev branch"
          git push origin HEAD

